Story2
Moukarnold/capstone-project pull request #12
Opened 2023-06-07 14:16 UTC by Moukarnold

creation of a new page , where the tongue twisters are displayed.
i add a function refresh

2023-06-07 15:12 UTC, MerleMak reviewed
Hi Arnold, 
I left you some comments :)
Nice work 🚀

2023-06-07 15:12 UTC, MerleMak commented on pages/api/gpt.js
> +    console.log("answer is", answer);
usually its common practice to delete console.logs before committing :)

2023-06-07 15:12 UTC, MerleMak commented on pages/index.js
> +          pathname: "/theDisplay",
I feel like you could come up with a better pathname :D

2023-06-07 15:12 UTC, MerleMak commented on pages/theDisplay.js
> +      <InnereBox>{tongueTwister && <p>{tongueTwister}</p>}</InnereBox>
Please stay consistent with your Component Naming. We want to write Components in the English language :) 
```suggestion
      <InnerBox>{tongueTwister && <p>{tongueTwister}</p>}</InnerBox>
```

2023-06-07 15:12 UTC, MerleMak commented on pages/theDisplay.js
> +          pathname: "/theDisplay",
If I understand correctly, what you want to do here is to generate a new page (and routing to a new page) each time you generate a new tongue twister. I think you should have a look at the Handout "Next Dynamic Routes", to find a better solution to this :)

2023-06-07 15:45 UTC, Moukarnold commented on pages/theDisplay.js
> +          pathname: "/theDisplay",
At this point the fetch is triggered by the button refresh. this fetch generates new sentences on the same page.

2023-06-07 15:47 UTC, Moukarnold commented on pages/index.js
> +          pathname: "/theDisplay",
ok ,  i will choose a better representativ name

2023-06-09 09:55 UTC, JohannSiemens reviewed
Good job Arnold, i would highly recommend you changing the data handling, because i think it's not necessary to pass them with the router.query.

2023-06-09 09:55 UTC, JohannSiemens commented on pages/api/gpt.js
> +    console.log("answer is", answer);
As far as i can tell, you still have this console.log in your code.

2023-06-09 09:55 UTC, JohannSiemens commented on pages/index.js
> +          pathname: "/theDisplay",
Is this going to part of a future refactoring? As far as i can tell, you still have the same pathname.

2023-06-09 09:55 UTC, JohannSiemens commented on pages/theDisplay.js
> +          pathname: "/theDisplay",
To me it looks like you are using the push.router to transport query-data (in this case the answer) from your fetch to the actual component. I would recommend you refactoring this to save the data in a state and then read it into the component itself. The push.router is to actually switch routes and the useState itself triggers a rerender (if i am not mistaken) so you don't actually need to use this type of implementation.

I just did a quick test on vercel with your current application version and i can manipulate the data by just switching the url-query parameters, which shouldn't be the case and also might be a potential security issue, especially if you start handling data in your backend.

2023-06-12 11:07 UTC, JohannSiemens reviewed
Hello Arnold, we talked about a potential refactoring of your application this morning. I would still recommend you to get rid of the data handling with the query and use a state instead, because a user can still use the query to manipulate your application and this is something you shouldn't allow. But you can also let a coach check our PR, maybe they have a different opinion on this topic, so i will leave the code-review "unchecked" in slack, to give the option for a more qualified opinion.

2023-06-12 11:15 UTC, Moukarnold commented
yes . i work on it

2023-06-12 12:25 UTC, NikRoe requested changes
Hi Arnold, 

I agree with Johann on how to transfer data within your app. I would also prefer having a state instead of using the router object.

If you want to set and read the state from within your `/pages/index.js` and want to read it from your `/pages/screening.js`, you have two options:
- work with a state management library like zustand or jotai
- move the state to the `/pages/_app.js` and pass it down as props (I would recommend this approach)

Apart from that, it looks really nice already and appears to become a fantastic app. Keep it up 🙌

2023-06-12 12:25 UTC, NikRoe commented on pages/index.js
> +      </form>
it makes semantically more sense for the inputs to be part of the form:

```suggestion
      <form onSubmit={handleSubmit}>
           <Languages onLanguage={handleNewLanguage} />
           <Themes onTheme={handleNewTheme} />
           <Difficulty onDifficulty={handleNewDifficulty} />
           <button type="submit">Obtenir une réponse</button>
      </form>
```

2023-06-12 14:39 UTC, JohannSiemens reviewed
Good refactoring Arnold, i just left you some comments. I can't really comment on you using useContext, because based on your depth within your component tree, you could easily use useState, but the documentation seem to also allow useContext for this matter.

2023-06-12 14:39 UTC, JohannSiemens commented on pages/screening.js
> +  const fetchTongueTwister = useCallback(async () => {
I personally don't see a reason for you using useCallback. After a quick research it seems like it's caching the function, which doesn't seem to make sense for you. You basically want to fetch your initial data and then fetch them again with the refresh button you created, so from my point of view there is no need to cache the function itself by using useCallback.

2023-06-12 14:39 UTC, JohannSiemens commented on pages/index.js
> +      </form>
Your form should be a "wrapper" around everything you want to have within it. I assume that the form isn't only the button itself, but also the data above it which you want to submit, so it should also be within the form element.

2023-06-12 14:39 UTC, JohannSiemens commented on pages/screening.js
> +  }, [fetchTongueTwister, config]);
I don't think you need this block of code here, because your drop-down input fields from the previous screen are required if i am not mistaken, so the useEffect here seems to be unnecessary, because your fetch is happening with the initial loading of your page and then again with the useEffect if your data validation is done. I would use the validation around the actual fetch, so it validates the config-data with every fetch, because they are necessary for every fetch.

2023-06-12 14:39 UTC, JohannSiemens commented on pages/screening.js
> +      <button onClick={handleRefresh}>Refresh</button>
button type="button" should be added here, because the default type variations are different between IE and other browsers.

2023-06-13 08:59 UTC, merged