Homepage
Moukarnold/capstone-project pull request #6
Opened 2023-05-25 08:29 UTC by Moukarnold

2023-05-26 07:59 UTC, Moukarnold commented
> i create a page language.
> 
> * i stored the language under the name storedlanguage
> * storedlanguage will be used later with the router.push(.....) to passing away as data for the API/ Fetch
> * english is setted as default language

2023-05-26 10:52 UTC, djfarly requested changes
Hej Arnold,

thank you for the PR!

Your app consists mostly of unconnected states and empty pages. For future PRs and stories please make sure that you are developing and actual feature.

You are representing all you selectable states as checkboxes. Please use a `<select>` element or a radio group to do so instead. (See comments below).

Keeping going!

2023-05-26 10:52 UTC, djfarly commented on pages/languages.js
> +  }, [language]);
Please do not roll your own local storage state implementation. Connecting state to local storage correctly is very hard and can lead to strange and hard to find bugs.

Please use the `use-local-storage-state` package we also used in the sessions. Check the the handouts for React with Local Storage to find out how to use it.

Basically all the code here can be simplified to:

```js
const [language, setLanguage] = useLocalStorageState("language", { defaultValue: "english" });
```

2023-05-26 10:52 UTC, djfarly commented on pages/Level.js
> +    console.log(level);
this console.log does not want to be merged :)

```suggestion
```

2023-05-26 10:52 UTC, djfarly commented on pages/Options.js
> +const spk = "simple Sentences and for kids";
It's strange that you have put this one option value into a variable while is directly in the JSX. Please consider having all options in an array and then mapping over that array in render.

Checkboxes are not the best way to represent a selection of one item. Please use a `<select>` element or radio buttons.



```js
const optionItems = [
  { label: "Simple Sentences & For Kids", value: "simple sentences and for kids"  },
  …
];
```

in the JSX:

```js
  <select name="options" onChange={(event) => handleOption(event.target.value)}>
    {optionItems.map((item) => (
      <option
        selected={options === item.value}
        value={item.value}
        key={item.value}
      >
        {item.label}
      </option>
    ))}
  </select>
```

2023-05-26 10:52 UTC, djfarly commented on pages/Options.js
> +    console.log(option);
snip
```suggestion
```

2023-05-26 10:52 UTC, djfarly commented on pages/languages.js
> +          </form>
See my comment above. Please us a select or radio buttons to represent this input.

2023-05-26 10:52 UTC, djfarly commented on pages/Level.js
>            </ContainerMainLabel>{" "}
this should be a select or radiogroup as well :)

2023-05-30 08:55 UTC, antoniatandler reviewed
I think this will work well! 😊

2023-05-31 09:29 UTC, merged